name: Test SSH Connection and Create File
on:
  workflow_dispatch: # Allows manual triggering of the workflow
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    - name: Test SSH Connection and Create File
      run: |
        ssh -o StrictHostKeyChecking=no mason@ninjastorm.firelab.org 'echo "SSH test successful" > ~/github_action_test.txt'
      # Replace `user` and `your-server-ip` with your actual SSH username and server IP
